### ISSUE TITLE
Additional step for getting binding offers

### ISSUE THREAD

**Issue by michschl** [swissfintechinnovations/ca-mortgage#11]
After multiple offers have been received, the tpp wants to get binding offers for just a few of them. This additional step seems to be important because the FIs usually have to block the money for the given binding offers.

**Comment by rolfwagner** [comment]
As discussed in Mortgage workshop of 21. Sept. 22: Please consider "binding valid until" functionality (input Nobert). 
It should be possible to communicate "win" / "loose" that FIs can release their reserverd amount as soon as possible.

**Comment by olegkovalov** [comment]
@rolfwagner, @pascalstockner There is one contradiction in the specification.
Please take a look on GET /mortgages/orders/{orderId}/status specifications. Order status could be rejected, but it shouldn't be possible if the offer is binding, and a customer got conditions with rates and "validTo" date. 
So in the order status response, I would propose to limit enum to ["accepted", "pending"] and remove "rejected" option
