### ISSUE TITLE
Mortgage API - Remove CH specifics

### ISSUE THREAD

**Issue by rolfwagner** [swissfintechinnovations/ca-mortgage#127]

**Comment by rolfwagner** [comment]
Next steps as discussed API Mortage meeting 30.01.23:

- Create a proposal / PR to "isolate" CH-specifics.

Lead: To be discussed in an SFTI weekly with Dominik

**Comment by dkoeni** [comment]
CH specifics need to be removed in order to submit the API for ISO standardization. This process is ongoing and discussed/aligned with the ISO committees. A procedure is worked out which is compatible with the ISO requirements and then applied to this API.
