### ISSUE TITLE
Default Reviewer

### ISSUE THREAD

**Issue by dkoeni** [swissfintechinnovations/ca-mortgage#131]
It might be helpful to auto assign default reviewers. This could be done via a CODEOWNERS file and adding all default reviewers to this file.

If you support this idea, I would create a branch to add default reviewers with all people you want to and make a PR.
I would suggest @rolfwagner @olegkovalov and @dkoeni as default reviewers, but we might add anyone else.

**Comment by rolfwagner** [comment]
done
