### ISSUE TITLE
Replacement including credit increase

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#132]
How do you handle/transfer data in the mortgage type replacement when the credit limit should be increased?

We would like to transfer:
- amount of increase
- purpose of increase
- withdrawn pension fund in past (question of handling in any case, also without credit increase)

We would recommend to add new fields:
- amount of increase in our TKB-Object "Financing" after the field "amount" and in the use case "financingRequest" after the field "amount" -> "increaseAmount"
- purpose of increase just after "increaseAmount" in both objects  ->"increasePurpose"
- transfer the amount of withdrawn pension fund in past in the UsedAssets with normal meccano (because UsedAssets is not used in the mortgagetype "Replacement", right?)

**Comment by rolfwagner** [comment]
Feedback SFTI Mortgage Meeting 16.12.2022:
- Basically ok
- To place in FinancingRequest

Please create PR.
