### ISSUE TITLE
New Field: Number Of Rooms In Granny Flat

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#14]
For Wüest Dimensions, we miss a field in "Property Objects":

field name: numberOfRoomsInGrannyFlat
description: The number of the rooms in the granny flat
not required
number, double

**Comment by rolfwagner** [comment]
@simonbbaumgartner : Please correct description - copy paste error (most probably)

**Comment by simonbbaumgartner** [comment]
done

**Comment by Adi-Moneypark** [comment]
I think we generally haven't touched that topic because it's rather a niche and ~mainIAZI version doesn't support it.
