### ISSUE TITLE
New Field: Environment Standard

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#15]
For the property estimation service (Wüest Dimensions and IAZ), we miss a field in "Property Building Information" (for single family houses):

field name: environmentStandard
description: The rating type
not required
string
enum: [high-level, basic, low-level]

**Comment by Adi-Moneypark** [comment]
I'm not sure which field of WuP you are referring to!?

**Comment by simonbbaumgartner** [comment]
derivationParametersHedStandard.environmentStandard| EnvironmentStandard | The standard of the environment
Mandatory Field only for val.method=HED_SFH and if grade.manualValue is NULL
(grade.manualValue is always NULL)

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
