### ISSUE TITLE
New Enum in Other Features in Property Building Information

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#16]
In the Field "otherFeatures" in the Object "Property Building Information"  for e.g. single family house some enum are missing for Wüest Dimensions. Could we please add the following enum:
indoor_pool, outdoor_pool, whirlpool_sauna, heated_conservatory, unheated_conservatory, security_system, chimney, passenger_elevator, freight_elevator

**Comment by Adi-Moneypark** [comment]
Code line 2049 in 2.3. Version

**Comment by simonbbaumgartner** [comment]
Code line 2049 in V2.3 or in V2.4 is only relevant for property**Flat**Information.
These enums are not just relevant for flat. They are needed for buildings (single family house) as well.
Therefore added in the object "propertyBuildingInformation": Code Line 2100 in V2.4

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
