### ISSUE TITLE
Grammar mistake in Other Features

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#17]
In the field "otherFeatures" in the object "propertyBuildingInformation" and in the object "propertyFlatInformation", there is a grammar mistake in the enum ventilation_system_without_min**g**ergie.
Could we correct that at both places?

**Comment by rolfwagner** [comment]
ok, please add (not replace) the enum with the correct spelling in your PR. Please create a additional issue to delete mistake enum in rls v3.0

**Comment by simonbbaumgartner** [comment]
done. pull request for next release with a new enum added is open.
new issue for release V3.0 is created, with no pull request so far.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
