### ISSUE TITLE
New Fields besides Object Price

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#18]
You know the field "objectPrice". In my view, this is the "Kaufpreis". Besides the "Kaufpreis" more types of amounts are relevant for an application.
Can we add the following amounts after "object Price":

- renovationAmount
  description: Amount needed to pay the planned renovation (Renovationsbetrag)
  Type: see "Amount"
- investmentCost
  description: Total amount needed to pay object price and planned renovation (Total Anlagekosten)
  Type: see "Amount"
- collateralValue
  description: Value of the property as base for the securization applying the lowest value principle (Belehnungsbasis)
  Type: see "Amount"
- limitForLandEncumbrances
  description: The limit for land encumbrance according to Bundesgericht über das bäuerliche Bodenrecht, SR 211.412.11 (Belastungsgrenze BGBB)
  Type: see "Amount"

**Comment by Adi-Moneypark** [comment]
General renovations are a current PR #56 I think.

We may already be able to send 2 different values, one as a result of evaluation for calculation and one is the cost (customer may "loose" own capital). 

Other Values are quite very detailed and may not be supported by a majority. Not mainstream business.

**Comment by simonbbaumgartner** [comment]
The first two fields are meant, how the applicant uses his assets:
- objectPrice (Kaufpreis der Liegenschaft) already in common api
- renovationAmount (Renovationen) not in common api so far (you might not have this use case)
- investmentCost (Anlagekosten as sum of objectPrice and renovationAmount) not in common api so far. Is not absolutely needed.

collateralValue: 
you are now able to send two values "objectPrice" and "amount" in Estimation. Due to the "Niederstwertprinzip" the bank needs to evaluate the "collateralValue", which is the lower of both of them. (It gets even more complicated to the "statisticalPriceRangeMax", "statisticalPriceRangeMin", see #20). we are able to provide the FI already with his relevant collateralValue. so the FI does not need to calculate himself.

limitforlandencumbrances is needed for agrar-financing.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
