### ISSUE TITLE
Renaming Estimation Amount - just description for V2.5 

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#19]
In the object "Estimation" you have the following fields:
- estimationSourceType
- amount
- estimationDate
 
Estimation tools like WuP and IAZI know several "amounts". Therefore the field "Amount" is not meaningful. I suggest to rather call this field "marketValue".

**Comment by rolfwagner** [comment]
Please add in your corresponding PR just a description for amount (= marketvalue). Create another issue for the renaming of amount into marktValue which we can plan for rls v3.0

**Comment by simonbbaumgartner** [comment]
PL-description: 'Estimated Market value of the property'
new Issue for Release 3.0 see #70

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
