### ISSUE TITLE
New Fields: Different Amounts in Estimation

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#20]
In the object "Estimation" I would like to add more fields to this object:
- statisticalPriceRangeMax
  description: Estimated statistical price range maximum
  type: see Amount
- statisticalPriceRangeMin
    description: Estimated statistical price range minimum
    type: see Amount
- yearlyRentalIncome
  description: Estimated rental income per year
  type: see Amount

**Comment by Adi-Moneypark** [comment]
Values are WP specific. Aks if majority support it. Also question about parking added to price range. 

Rental income was discussed before but a too detailed for the current API-level because we are focused on selfowned property. I recoommend this for 3.0 version.

**Comment by simonbbaumgartner** [comment]
these values are all provided by WüestDimensions in the estimation tool. We can provide them to the FI. espescially the price range is relevant. price range is also provided by IAZI.

yearly rental income is also estimated by WüestDimensions. So, why not transfer the data to the FI?

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
