### ISSUE TITLE
Inconsistency in Duration

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#22]
«Duration» at «Mortgage Product Variation» - Type: integer, int32, 1-20
«Duration» at «Mortgage Product Condition» - Type: string
«Duration Type» at "Mortgage": 1-10

How come that we have two fields "duration"? Is that technically no problem?
Do we need to rename?

What should we fill in the field if the mortgage has no duration (SARON or variable)?
FI can potentially offer fixed mortgage longer than 10 year, e.g. 20 years
We should allign the types of these 3 fields: "0-20" or just "string" without enum.

**Comment by Adi-Moneypark** [comment]
WIthout getting all the details of this comment. SARON has two durations, one for the overall contract duration (e.g. 5 years) and one for the product subtype (e.g. 3 months renewal interval)

**Comment by simonbbaumgartner** [comment]
the "saron renewal interval" should not be "duration". This is the field "saronperiod" in the object "ProductVariation"

**Comment by rolfwagner** [comment]
Discussion 21.09.22:

- Harmonize to "Duration" to type integer 0-25
--> Rls3
