### ISSUE TITLE
New Field: Start Date

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#24]
You have the field "MaturityDate". I miss the field "StartDate" for the indication, when the mortgage starts.
Could we please have this new field before the field "MaturityDate"?

Type: see Date

**Comment by Adi-Moneypark** [comment]
Isn't this already part of a PR (change of ownership vs. public notarisation)?

**Comment by simonbbaumgartner** [comment]
Should be something else. Change of ownership/public notarisation is only applicable in the mortgagetype "buy". We need a startDate of the mortgage, not only for mortgagetype "buy" but also for "replacement".

**Comment by simonbbaumgartner** [comment]
Start Date not needed. There is the field: payoutDate. This is sufficient.

**Comment by stjosh** [comment]
@simonbbaumgartner Does that mean we can close this issue and #74?
