### ISSUE TITLE
New Enum in Mortgage Type

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#29]
In addition to the enum "buy" and "replacement" we consider "Baufinanzierung" as well as a mortgage type.

In "mortgageType", we would like to extend the enum by "construction_financing".

**Comment by Adi-Moneypark** [comment]
Topic for 3.0 or even later. Will not fit the idea of standard requests and a construction request may not be able to provide all mandatory fields...

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
