### ISSUE TITLE
New Fields: Applicant Rating

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#31]
Our service transfers data on the rating/solvency (CRIF Score) to the FI. We would like to have relevant fields in the object "Applicant":
- rating
   description Solvency rating of the applicant
   type: integer
- ratingDate
  description: Date of the solvency rating
  type: see Date

**Comment by Adi-Moneypark** [comment]
So far, FI (Credit Suisse) is doing the check and not TPP. Sidenote: They get better rates at CRIF. 
We are open for a possible overall solution but from experience, most FI don't use the score.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: 

added an additional field: ratingSourceType with enum: crif

Ok
