### ISSUE TITLE
New Enum in Marital Status

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#32]
We have two more options of "marital status":
- legally separated - gerichtlich getrennt
- Partnership dissolved - aufgelöste Partnerschaft 

Could we add these to the enum?

**Comment by Adi-Moneypark** [comment]
Why not. Difference between these two?

**Comment by simonbbaumgartner** [comment]
gerichtlich getrennt:
Die gerichtliche Trennung ist, wie die Scheidung, ein gesetzlich anerkannter Status. Bei der gerichtlichen Trennung wird das gemeinsame Leben der Ehegatten durch ein Gerichtsurteil beendet, d.h. es ist die Intervention einer Richterin bzw. eines Richters erforderlich. Das Verfahren ist ähnlich wie bei einer Scheidung. Im Unterschied zur Scheidung löst das Urteil über die gerichtliche Trennung die Ehe jedoch nicht auf . Das Konzept der gerichtlichen Trennung wurde in erster Linie eingeführt, um katholischen Ehepartnern die Möglichkeit zu geben, ihren Zivilstand mit dem Glauben zu vereinbaren. Zudem bietet die gerichtliche Trennung einem Paar mit Eheproblemen eine Bedenkzeit, bevor es die Ehe definitiv auflöst.

aufgelöste Partnerschaft:
Die Partnerin oder der Partner, die bzw. der eine Auflösung der eingetragenen Partnerschaft wünscht, kann beim Gericht einen entsprechenden Antrag stellen. Entscheidend für die einzelnen Schritte ist, ob die Trennung von beiden oder nur von einer Person gewollt ist. Die eingetragene Partnerschaft kann auch gegen den Willen einer Partnerin oder eines Partners aufgelöst werden. Wenn das Paar seit einem Jahr getrennt lebt, kann die Person, die die Partnerschaft auflösen will, eine sogenannte Auflösungsklage einreichen.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
