### ISSUE TITLE
New Field: Residential Situation

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#33]
For the FI it makes a difference in the affordability calculation if the applicant is renter or home_owner. depending on that the bank needs to consider other costs.

Therefore, we would like to have a new field in the object "Financial Situation":
name: residentialSituation
Type: string, enum: [home_owner, renter]

**Comment by Adi-Moneypark** [comment]
As mentioned, so far focus was on selfowned property. But rented object are on our agenda for the future.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
