### ISSUE TITLE
New Enum in Asset Type

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#35]
An applicant of a mortgage can bring unpledged building plot as part of his assets (Eigenmittel). This enum is missing in the assetType.

Please add the enum: unpledged_building_plot

**Comment by Adi-Moneypark** [comment]
Not sure if this is a "mainstream" thing. AssetType "other" is available.

**Comment by simonbbaumgartner** [comment]
Unpledged Building Plot is not mainstream. Can be reality, though. The more precise, the better.
AssetType "other" is not available. see Code line 2677-2694

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
