### ISSUE TITLE
New Enum in Income Types

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#37]
Some options are missing in the enum of the "income Types": leasing_payment, consumer_loan_payment, child_allowance_payment, rental_costs, costs_for_additional_properties

Please add these to the enum.

**Comment by Adi-Moneypark** [comment]
I thing the first three are available (Leasing and consumer loan are "merged" on our side for Valiant resp. sent as "other" for CS). Code line 2651 in 2.3. version. The last two are future topic when including rented objects.
