### ISSUE TITLE
New Field: Phone in Applicant Detail

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#38]
Besides email of the applicant, the FI needs to know a phone number. So, we want to add a new field in the applicant Detail:
Name: phone
Description: Phone Number of the applicant
Type: string

**Comment by Adi-Moneypark** [comment]
Code line 2478 of 2.3. version.

**Comment by simonbbaumgartner** [comment]
in V2.4: not available for applicant. Phone just available for TPP Advisor

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
