### ISSUE TITLE
New Setup: Property Renovation

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#39]
Wüest Dimensions differentiates not just renovation: true/false. Wüest Dimensions has different refurbishment Component Types:
total, interior_fittings_kitchen, interior_fittings_bathroom_sanitary, interior_fittings_floor_cover, interior_fittings_remaining
building_envelope_pitched_roof, building_envelope_flat_roof, building_services_heat_production, building_services_heat_emission, buildings_services_electrical_ventilation_elevator, work_on_surroundings, supporting_structure, building_envelope_windows, building_envelope_facade_balcony

renovation should therefore be built as an own object with a list/array: 
- refurbishmentComponentType (string, enum: see above)
- yearOfRenovation (same as "renovationYear" but different name)
- renovationCost (see your Standard for "amount")

**Comment by simonbbaumgartner** [comment]
should we delete the field "renovationYear" in Release 3.0?

**Comment by Adi-Moneypark** [comment]
~Main IAZI-Version uses just a year, without amounts or what was renovated for it's evaluation

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
@olegkovalov, could you please review the PR and give feedback on the technical part of this issue.

**Comment by simonbbaumgartner** [comment]
To cover the simple renovation GUI of Wüest Partner, I added the following enum: interior_fittings / building_envelope / building_services 
To make the handling of the two different WP-renovation GUI clear, I adjusted the descpription.
