### ISSUE TITLE
New Field: Luxus Flag

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#40]
For IAZI-estimations, the luxus flag is in "propertyObject" needed.
Name: luxusFlag
Description: If the property is luxury
not required field
String, enum: [0, 0.5, 1.0]
0 = Nein
0.5 = Teilweise
1.0 = Ja

**Comment by Adi-Moneypark** [comment]
Value for "Building_condition" should be transmitted. 
IAZI providers should do a mapping on their side of WP value (1.0 - 5.0) 
My suggestion:
4.1 - 4.5 ==> partially luxury (0.5)
4.6 - 5.0 ==> Fully luxury (1.0)

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
