### ISSUE TITLE
New Enum in Minergie Standard Type

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#41]
Besides the current enum (none, minergie, minergie-p, minergie-eco, minergie-p-eco) IAZI now works with two additional minergieStandardTypes:
- minergie-a
- minergie-a-eco

We should accept this two new types in our enum in the field "minergieStandardType".

**Comment by Adi-Moneypark** [comment]
OK, wasn't aware of that

**Comment by simonbbaumgartner** [comment]
we are open for a new field GEAK, needs a new issue.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
