### ISSUE TITLE
New Field: Property Type

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#42]
We miss a field in "Property Objects":
field name: propertyType
description: The type of property
not required
string
enum: [single_family_house, condominium, vacation_house, vacation_condominium, agricultural_farm, 2or3_family_house, multi_family_house, residential_building_plot, building_plot_other, mixed_property, commercial_condominium, office_building, industrial_building, special_object]

**Comment by Adi-Moneypark** [comment]
I am unaware of agricultural_farm or 2or3_family_house being part of WP or IAZI in the normal evaluation. 
For me more category "income_property".

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
