### ISSUE TITLE
New Field: Heat Production

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#45]
For Wüest Dimensions estimations, we miss a field in "Property Objects":

field name: heatProduction
description: Type of the heat production
not required
array
string
enum: [oil, gas, wood, electric, geothermal_probe, district, solar_panel, solar_thermal_collector]

**Comment by Adi-Moneypark** [comment]
I thought we have it already but seem no. More relevant than ever.

**Comment by simonbbaumgartner** [comment]
Agreement MP / TKB on 29.09.22: Ok
