### ISSUE TITLE
Assets and UsedAssets

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#47]
How do you differentiate between asset and used asset?

e.g. if the applicant has cash CHF 200'000 and thereof he uses CHF 150'000 for financing the property as "Eigenmittel".
do you enter
CHF 200'000 in the "assets" in "financialSituation" as "assetType" cash
and CHF 150'000 in the "usedAsset" in "FinancingRequest" as "assetType" cash and "assetUsageType" withdraw?

If so, this makes sense. For new participants in the Common API community, this should be documented somewhere.

**Comment by Adi-Moneypark** [comment]
I can say it worked for CS.

**Comment by simonbbaumgartner** [comment]
good setup. thank you

**Comment by simonbbaumgartner** [comment]
Proposed description in "assets" in the object "financial Situation":
'Array of all assets the applicant possesses, incl. the assets which will be used for the financial request.'

Proposed description in "usedAssets" in the object "Financing Request":
'Array of all assets which will be used for the financial request. At least, all of these used assets must also be recorded in the array of assets in the financial situation of one applicant.'
