### ISSUE TITLE
Including Conditions in the mortgage

### ISSUE THREAD

**Issue by simonbbaumgartner** [swissfintechinnovations/ca-mortgage#93]
If we include conditions in the object "mortgage" or in the object "mortgage product", we could (besides information about the product) also transfer duration, maturity date, interest, amount range, increment, and the newly added information about amortization and the datepricefixing. 

Where should we implement it: mortgage oder mortgage product? 
Description of the field is: "All details regarding the conditions for a specific mortgage product the FI offers"
this would be a reason to put it into mortgage product. another reason is that, we could also transfer the integrated information in the use case "Offer".

If we implement it, we could also delete the following fields in "mortgage": validFrom, validTo, interestRate, durationType. is that right?

**Comment by rolfwagner** [comment]
Feedback SFTI Mortgage meeting:

- To be analyzed in detail (MP). Possible enhancement for Rls4.x
